bind_addr = "0.0.0.0:3000"

[compiler]
rrc_path = "/opt/reussir/bin/rrc"
rene_path = "/opt/reussir/bin/rene"
llvm_strip_path = "/usr/bin/llvm-strip"
rustc_path = "/opt/cargo/bin/rustc"
cargo_path = "/opt/cargo/bin/cargo"
build_dir = "/var/lib/reussir-playground/rene"
cargo_home = "/var/lib/reussir-playground/rene/cargo-home"
toolchain_ro_paths = ["/opt/rustup", "/opt/cargo"]
compile_timeout_secs = 30
build_timeout_secs = 300

[sandbox]
kind = "landlock"
